packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: false
  workerd: true

catalogMode: strict

overrides:
  libsodium-sumo: 0.8.4

minimumReleaseAgeExclude:
  - hono@4.12.32

catalog:
  '@scure/base': 2.2.0
