export {
  createEncryptedVaultArchive,
  type EncryptedVaultArchiveV1,
  openEncryptedVaultArchive,
  type VaultArchiveContentsV1,
} from "./archive";
export { parseVaultHeader } from "./header";
export {
  createEncryptedItemRevision,
  createEncryptedTombstone,
  type EncryptedItemRevisionV1,
  type IdentityProfileItem,
  type IdentityProfileItemInput,
  ItemError,
  type ItemErrorCode,
  type ItemRevisionRepository,
  type LoginItem,
  type LoginItemInput,
  type OrganizationInput,
  openEncryptedItemRevision,
  type PasswordBreachCheck,
  type PaymentCardItem,
  type PaymentCardItemInput,
  parseEncryptedItemRevision,
  parseIdentityProfileInput,
  parseLoginInput,
  parsePaymentCardInput,
  parseSecureNoteInput,
  type SecureNoteItem,
  type SecureNoteItemInput,
  type VaultItem,
} from "./items";
export { decodeRecoveryKit, encodeRecoveryKit } from "./recovery";
export {
  type EncryptedSearchIndexV1,
  encryptSearchIndex,
  searchEncryptedIndex,
} from "./search";
export {
  type CreateVaultServiceOptions,
  createVaultService,
  type KdfCalibrationOptions,
  type VaultSessionOptions,
} from "./service";
export {
  type CreatedEncryptedItemShare,
  createEncryptedItemShare,
  type EncryptedItemShareV1,
  ItemShareError,
  type ItemShareErrorCode,
  openEncryptedItemShare,
} from "./share";
export {
  type ActiveDeviceSlot,
  type ActiveDeviceSlotV1,
  type ActiveDeviceSlotV2,
  type ChangeMasterPasswordRequest,
  type DeviceSlotSummary,
  type DeviceSlotV1,
  type DeviceUnlockSummary,
  EMPTY_VAULT_SCHEMA_VERSION,
  type EmptyVaultPayloadV1,
  ENVELOPE_VERSION,
  type EncryptedEnvelope,
  type EncryptedEnvelopeV1,
  type EnvelopePurpose,
  type KeyKind,
  type MasterPasswordSlotV1,
  type MasterPasswordSlotV2,
  type PasswordKdfV1,
  type RecoveryKitSlotV1,
  type RecoveryPublicState,
  type RestoreVaultRequest,
  type RevokedDeviceSlotV1,
  type SensitiveCompartment,
  type StepUpCredential,
  TASK3_VAULT_SCHEMA_VERSION,
  type Task3VaultPayloadV2,
  VAULT_HEADER_FORMAT,
  VAULT_HEADER_VERSION,
  VAULT_HEADER_VERSION_V1,
  VAULT_MINIMUM_CLIENT_VERSION,
  VAULT_MINIMUM_CLIENT_VERSION_V1,
  type VaultClient,
  VaultError,
  type VaultErrorCode,
  type VaultHeader,
  type VaultHeaderRepository,
  type VaultHeaderV1,
  type VaultHeaderV2,
  type VaultHeaderWriteCondition,
  type VaultItemHistoryEntry,
  type VaultPublicState,
  type VaultSessionMaterialV1,
  type WrappedKeySetV1,
} from "./types";
